### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by AdamYLiang** [elvis-yuan/Disco-RD#4]
- [x] No need to have `/servers/:serverId/channels/new` since we can use a modal/ui slice of state to control when the form to make channels show up.

**Comment by elvis-yuan** [comment]
Fixed, Should new servers also be a modal?

**Comment by AdamYLiang** [comment]
Good catch, let's make that a modal as well. 
- [ ] `servers/new` can be replaced with modal on main servers page

**Comment by elvis-yuan** [comment]
Fixed
