### ISSUE TITLE
User Auth MVP

### ISSUE THREAD

**Issue by AdamYLiang** [elvis-yuan/Disco-RD#5]
- [x] Automatically log the user in when they create a new account, right now it redirects them to the login page. Theres also a 404 error when you try to log the user out right after signing in but this will be fixed once we properly log the user in since in the backend the user is not logged in but the front end thinks the user is logged in. 
- [x] Revisit routes for login since right now if you hit the back button after logging in it renders a white page. 

**CSS**
- [x] `Open` button in top right of splash page should be whiter 
- [x] Create own logo for Disco-RD

Let me know if you have any questions!

**Comment by AdamYLiang** [comment]
- [ ] Errors on login/signup should have text error message to inform user what went wrong.

**Comment by elvis-yuan** [comment]
Fixed

**Comment by AdamYLiang** [comment]
Nice logo!
