### ISSUE TITLE
Servers MVP

### ISSUE THREAD

**Issue by AdamYLiang** [elvis-yuan/Disco-RD#6]
Hi there Elvis! 

- [x] In the dropdown for clicking server name, have an option for user to leave the server like on the original app. 
- [x] There is a rare bug where the page doesn't change on logout, so I'm still in the main app while logged out. It seems to happen if I make a server/channel and edit around. I'll keep poking around and see if I can find exact steps to reproduce this error. 

**CSS**
- [x] Style dropdown for clicking the channel name for invite code. Discord uses a white background with blue text. For now it can hold the same information but later down the line we should have the same dropdown buttons.

**Comment by elvis-yuan** [comment]
fixed
