### ISSUE TITLE
Channels MVP

### ISSUE THREAD

**Issue by AdamYLiang** [elvis-yuan/Disco-RD#7]
- [x] After editing a channel, the channel jumps to the top of the channel list. Consider finding a way to keep the order of the channels.
- [x] Have buttons next to the user for voice/mute/settings. Doesn't have to function right now.
 
If you want to play around with AWS you could start the feature for adding custom photos/pictures to servers and users.

**Comment by elvis-yuan** [comment]
fixed the issue on my local build will push up the most stable version
